TrixiEther/Dashchan-Extensions

- extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachChanPerformer.java
> Passcodu fix

- extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachChanPerformer.java
> Fix | Main and userboards

- extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachChanPerformer.java
Icons working(again?)
Closes #9
> Fix | usericons

- extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachChanPerformer.java
- extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachModelMapper.java
The search works as it was, but with a separate call for each found post
So requests that are too general may take longer or cause a 500 error - too many requests.
> Fix | Search

- extensions/dvach/build.gradle
Modification to remote and local build config
> Fix | Dvach build

- extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachChanPerformer.java
Обезьяна иногда возвращает некорректый код ошибки. Например, 0 (в документации к API это значит "NoError, ошибки нет") вместо 6 ("ErrorBanned, вы были забанены") если забанен за прокси\впн. В таких случаях можно проверить сообщение об ошибке на наличие слов, которые обычно есть в сообщение о бане, и по результатам проверки сделать вывод, забанен ли постер или это какая-то неизвестная ошибка.
> Фикс сообщения о бане на Дваче

- extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachChanConfiguration.java
> TrixiEther | Enhanement | Captcha-TLL

- extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachChanPerformer.java
Добавил условие, что если вместо изображения капчи сервер вернул ошибку 500, то нужно повторить попытку после задержки 0.5 сек. Если не получится получить изображение капчи за 3 попытки или код ошибки не 500 - выбрасывается исключение. 
Можно будет откатить это изменение, когда обезьяна починит капчу.
> dvach: Retry loading captcha if get HTTP error 500

- extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachChanPerformer.java
Не особо разбираюсь в регулярных выражениях, но, вроде, этот шаблон подходит ко всем вариантам сообщения о бане ([Несколько примеров](https://regex101.com/r/e82JbM/2)). Если соответствие всё-таки не найдено - используется всё сообщение целиком.
Основная цель этого изменения - возвращение даты разбана.
> dvach: Change ban message regex pattern to match new ban message

- extensions/endchan/res/values-ru/strings.xml
- extensions/endchan/res/values/strings.xml
- extensions/endchan/src/com/mishiranu/dashchan/chan/endchan/EndchanChanPerformer.java
- Починил капчу.
- Реализовал обход блокировки IP адреса если есть возможность.
- Если пользователь забанен, то теперь выбрасывается соответствующее исключение исключение вместо "Некорректный ответ сервера". Пока что без подробностей бана, потому что не было возможности проверить, что отвечает сервер в случае бана.
> Endchan posting fix

- extensions/cirno/src/com/mishiranu/dashchan/chan/cirno/CirnoChanPerformer.java
- extensions/cirno/src/com/mishiranu/dashchan/chan/cirno/CirnoFirewallResolver.java
> cirno: Implement firewall resolver

- engines/vichan/src/chan/content/VichanChanLocator.java
- extensions/refugedobrochan/build.gradle
- extensions/refugedobrochan/src/com/trixiether/dashchan/chan/refugedobrochan/RefugeDobrochanChanLocator.java
Fixed, but with reservations...
Vichan doesn't seem to be able to return JSON for a SinglePost, so if the link refers to a post that's in another thread, or it's not explicitly opened, the app will offer to open the thread instead of loading the post separately
Closes #38 
Closes #39
> TrixiEther | Refuge Dobrochan links issues

- .github/workflows/android.yml
- extensions/archivedmoe/build.gradle
workflow and build.gradle configured
> TrixiEther | archived.moe

- .github/workflows/android.yml
Dummy commit for good luck lol
> TrixiEther | Workflow - move to matrix strategy builds

- extensions/dollchan/build.gradle
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanChanLocator.java
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanPostsParser.java
Fix multiple pages support for dollchan
Fix time parsing for dollchan
> Dollchan 1.2

- extensions/dollchan/build.gradle
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanPostsParser.java
> Dollchan: detection of sticky, cyclical threads, likes count

- extensions/dollchan/build.gradle
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanChanConfiguration.java
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanChanPerformer.java
This change:
- Fixes deletion of own posts
- Implements user authorization (only mods for now)
- Adds some moderation tools (for mods) to allow deletion & moderation thru "report" option.
> dollchan: own post deletion & moderator support

- extensions/dollchan/build.gradle
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanChanConfiguration.java
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanChanPerformer.java
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanPostsParser.java
* Likes counter triggets a lot of "Some posts have been edited" popups, so removed.
* dollchan.net/ukr has preview for videos now, but dashchan fails to pick them up, so fixed
* some additional moderation tools
* bump version to 1.5
> Dollchan 1.5

- extensions/dollchan/build.gradle
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanChanConfiguration.java
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanChanPerformer.java
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanPostsParser.java
- Passcode support (you should receive your on your email)
- Properly displaying admins & mods
- Dynamic board list
> Dollchan 1.6

- extensions/dollchan/build.gradle
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanChanConfiguration.java
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanChanPerformer.java
A warning moderation action (under Report section).
Also, add rigidity, in case board list turns out empty, display static list.
> Dollchan moderation tools (warning)

- extensions/dollchan/build.gradle
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanChanConfiguration.java
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanChanPerformer.java
- extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanPostsParser.java
Dollchan update 1.8:
- post’s image size and simensions
- post date
- mod reporting tools (subnet ban)
- regular reporting (for users)
> Dollchan 1.8: image info, post dates, user reporting

- extensions/sojakparty/src/com/mishiranu/dashchan/chan/sojakparty/SojakpartyChanConfiguration.java
- extensions/sojakparty/src/com/mishiranu/dashchan/chan/sojakparty/SojakpartyChanPerformer.java
Currently loads the threads JSON raw in browser for some reason. Setting a user agent seems to fix this. Also adds more file types that can be uploaded.
> Fix soyjak.party loading

- extensions/sojakparty/res/values/strings.xml
- extensions/sojakparty/src/com/mishiranu/dashchan/chan/sojakparty/SojakpartyChanConfiguration.java
- extensions/sojakparty/src/com/mishiranu/dashchan/chan/sojakparty/SojakpartyChanMarkup.java
- extensions/sojakparty/src/com/mishiranu/dashchan/chan/sojakparty/SojakpartyChanPerformer.java
- extensions/sojakparty/src/com/mishiranu/dashchan/chan/sojakparty/SojakpartyModelMapper.java
- Removes KAPTCHA (no longer owned by the admin who made it)
- Support embeds
- Support more text styles (uses emojis to distingush similar styles as there is not support for text shadows or gradients)
> soyjak.party: support embeds, more text styling

- extensions/refugedobrochan/build.gradle
- extensions/refugedobrochan/src/com/trixiether/dashchan/chan/refugedobrochan/RefugeDobrochanChanMarkup.java
I noticed that the latest release version of the DobrochanRefuge extension contains incorrect markup tags. This PR contains currently relevant markup tags.
> DobrochanRefuge: markup support

- extensions/dvach/res/values-ru/strings.xml
- extensions/dvach/res/values/strings.xml
- extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachChanConfiguration.java
- extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachChanPerformer.java
- extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachEmojiCaptchaProvider.java
2ch.hk made new type of captcha, which is available for now in /test/: https://2ch.hk/test/
This PR add support of this captcha in dashchan 2ch extension.
https://github.com/user-attachments/assets/48aa8c09-0131-4b10-9688-706232e2965d
> Support emoji_captcha for 2ch.hk
